(function(KG){
  'use strict';
  const {overlap,clamp}=KG.Math;
  class Game {
    constructor(canvas,assets,save,audio,input){
      this.canvas=canvas;this.assets=assets;this.save=save;this.audio=audio;this.input=input;this.renderer=new KG.Renderer(canvas,assets,save);this.ui=new KG.UI(this,save);
      this.mode='menu';this.levelIndex=0;this.level=KG.Levels[0];this.world=null;this.player=null;this.score=0;this.lives=3;this.missionDoneCount=0;this.missionTarget=0;this.missionDone=false;
      this.cameraX=0;this.cameraLead=0;this.levelTime=0;this.last=performance.now();this.acc=0;this.step=1/120;this.finishLatch=false;
      this.combo=0;this.comboTimer=0;this.queryAutostart=new URLSearchParams(location.search).get('autostart')==='1';
    }
    boot(){this.ui.refreshMenu();this.ui.setHUD(false);document.getElementById('loading-screen').classList.add('hidden');document.getElementById('menu-screen').classList.remove('hidden');if(this.queryAutostart){document.getElementById('menu-screen').classList.add('hidden');this.startLevel(Number(new URLSearchParams(location.search).get('level')||0),true);}requestAnimationFrame(t=>this.loop(t));}
    startLevel(index,newRun=false){index=clamp(index,0,4);this.ui.setHUD(true);['menu-screen','level-screen','pause-screen','complete-screen','gameover-screen','victory-screen'].forEach(id=>document.getElementById(id).classList.add('hidden'));if(newRun||this.mode==='menu'){this.score=0;this.lives=3;}else this.lives=3;this.levelIndex=index;this.level=KG.Levels[index];this.world=new KG.World(this.level,this.audio,this.save);this.player=new KG.Player(this.level.spawn[0],this.level.spawn[1]);this.player.setCheckpoint(this.level.spawn[0],this.level.spawn[1]);this.missionTarget=this.level.ball?1:this.level.boss?5:this.level.mission.length;this.missionDoneCount=0;this.missionDone=false;this.cameraX=0;this.cameraLead=0;this.levelTime=0;this.finishLatch=false;this.combo=0;this.comboTimer=0;this.mode='playing';this.ui.toast(`${this.level.name} · ${this.level.objective}`,2500);this.ui.updateHUD(this);}
    goMenu(){this.mode='menu';this.ui.setHUD(false);document.getElementById('menu-screen').classList.remove('hidden');document.getElementById('boss-wrap').style.display='none';this.ui.refreshMenu();}
    togglePause(force){if(!this.world)return;const pause=force===undefined?this.mode==='playing':force;if(pause&&this.mode==='playing'){this.mode='paused';this.ui.showPause();}else if(!pause&&this.mode==='paused'){this.mode='playing';this.ui.hidePause();}}
    resetCombo(){this.combo=0;this.comboTimer=0;this.ui.updateCombo(this);}
    hurt(kind='normal'){if(this.player.invincible>0)return;this.resetCombo();this.lives--;this.player.invincible=1.4;this.audio.sfx(kind==='water'?'splash':'hurt');this.renderer.shake=kind==='water'?8:13;this.renderer.flash=kind==='water'?.25:.6;this.ui.toast(this.lives>0?(kind==='water'?'Плюх! Возвращаемся к контрольной точке.':'Осторожно! Потеряна жизнь.'):'Жизни закончились.');if(this.lives<=0){this.mode='gameover';this.ui.showGameOver();}else this.player.respawn();this.ui.updateHUD(this);}
    collect(it){if(it.type==='coin'){this.save.addCoins(1);this.score+=50;this.audio.sfx('coin');this.renderer.addParticles(it.x,it.y,'#ffd15b',8);}else{this.missionDoneCount++;this.score+=120;this.audio.sfx('collect');this.renderer.addParticles(it.x,it.y,'#ffb765',10);if(this.missionDoneCount>=this.missionTarget){this.missionDone=true;this.ui.toast('Задание выполнено! Ищи выход.',2100);}}this.ui.updateHUD(this);}
    stomp(enemy){this.combo=Math.min(5,this.combo+1);this.comboTimer=2.1;const mult=1+(this.combo-1)*.35;const pts=Math.round(180*mult);this.score+=pts;this.audio.sfx(this.combo>=2?'combo':'stomp');this.renderer.addParticles(enemy.x,enemy.y,'#b894ff',9+this.combo*2);this.renderer.shake=4+this.combo*1.5;this.ui.updateCombo(this);if(this.combo>=2)this.ui.toast(`Комбо x${this.combo} · +${pts}`,850);}
    complete(){if(this.finishLatch)return;this.finishLatch=true;this.mode='complete';this.audio.sfx('win');this.save.unlockLevel(this.levelIndex+1);this.save.setScore(this.score);let stars=1;if(this.levelTime<=this.level.par*1.15)stars=2;if(this.levelTime<=this.level.par&&this.lives===3)stars=3;this.save.setStars(this.levelIndex,stars);this.ui.showComplete(stars,this.levelTime);}
    showVictory(){this.mode='victory';this.audio.sfx('bossWin');this.save.setScore(this.score);this.ui.showVictory();}
    update(dt,time){if(this.input.consumePause())this.togglePause();if(this.mode!=='playing')return;this.levelTime+=dt;if(this.comboTimer>0){this.comboTimer-=dt;if(this.comboTimer<=0)this.resetCombo();}this.world.update(dt,time,this.player);this.player.update(dt,this.input,this.world,this.audio);if(this.player.y>1000)this.hurt('water');const water=this.world.checkWater(this.player);if(water&&this.player.invincible<=0){this.renderer.addSplash(water.x,water.y);this.hurt('water');}if(this.world.checkHazards(this.player))this.hurt();const ec=this.world.checkEnemyCollisions(this.player);if(ec){if(ec.type==='hurt')this.hurt();else this.stomp(ec.enemy);}const got=this.world.collect(this.player,time);got.forEach(it=>this.collect(it));if(this.world.checkpoint(this.player)){this.audio.sfx('checkpoint');this.renderer.addParticles(this.player.x,this.player.y-35,'#8ee6ff',14);this.ui.toast('Контрольная точка!');}if(this.world.ball&&this.world.basket&&this.missionDoneCount===0){const b=this.world.ball,bs=this.world.basket;if(b.x>bs.x+18&&b.x<bs.x+bs.w-18&&b.y>bs.y-70&&b.y<bs.y+bs.h){this.missionDoneCount=1;this.missionDone=true;this.score+=300;this.audio.sfx('win');this.ui.toast('Шар в корзине!');this.ui.updateHUD(this);setTimeout(()=>this.complete(),250);}}if(this.world.boss&&!this.world.boss.dead){const boss=this.world.boss;if(overlap(this.player.box(),boss.box())&&this.player.invincible<=0){if(boss.vulnerable&&this.player.vy>0&&this.player.y-this.player.h<boss.y-boss.h+40){boss.hp--;boss.flash=.3;this.player.vy=-630;this.score+=500;this.missionDoneCount=boss.maxHp-boss.hp;this.audio.sfx('boss');this.renderer.shake=11;this.renderer.addParticles(boss.x,boss.y-110,'#ff704f',18);this.ui.toast(`Попадание! Осталось ${boss.hp} HP`);this.ui.updateHUD(this);if(boss.hp<=0){boss.dead=true;this.missionDone=true;setTimeout(()=>this.complete(),700);}}else if(boss.state!=='shield')this.hurt();}}this.world._lastPlayerX=this.player.x;if((this.level.goalX&&this.missionDone&&this.player.x>this.level.goalX-65)||(this.level.house&&this.missionDone&&this.player.x>this.level.house[0]-80))this.complete();const desiredLead=clamp(this.player.vx*.34,-105,105);this.cameraLead+=(desiredLead-this.cameraLead)*Math.min(1,dt*3.4);const anchor=this.renderer.w*.39;let target=this.player.x-anchor+this.cameraLead;const screenX=this.player.x-this.cameraX,deadLeft=this.renderer.w*.30,deadRight=this.renderer.w*.58;if(screenX>deadLeft&&screenX<deadRight&&Math.abs(this.player.vx)<150)target=this.cameraX;target=clamp(target,0,Math.max(0,this.level.width-this.renderer.w));this.cameraX+=(target-this.cameraX)*Math.min(1,dt*5.2);this.renderer.updateParticles(dt);this.audio.update(dt,this.mode);this.ui.updateHUD(this);}
    loop(now){const frame=Math.min((now-this.last)/1000,.05);this.last=now;this.acc+=frame;const time=now/1000;while(this.acc>=this.step){this.update(this.step,time);this.acc-=this.step;}if(this.world)this.renderer.render(this,time);requestAnimationFrame(t=>this.loop(t));}
  }
  KG.Game=Game;
})(window.KG = window.KG || {});
