(function(KG){
  'use strict';
  const {overlap,clamp}=KG.Math;
  class Game {
    constructor(canvas,assets,save,audio,input){this.canvas=canvas;this.assets=assets;this.save=save;this.audio=audio;this.input=input;this.renderer=new KG.Renderer(canvas,assets,save);this.ui=new KG.UI(this,save);this.mode='menu';this.levelIndex=0;this.level=KG.Levels[0];this.world=null;this.player=null;this.score=0;this.lives=3;this.missionDoneCount=0;this.missionTarget=0;this.missionDone=false;this.cameraX=0;this.levelTime=0;this.last=performance.now();this.acc=0;this.step=1/120;this.finishLatch=false;this.queryAutostart=new URLSearchParams(location.search).get('autostart')==='1';}
    boot(){this.ui.refreshMenu();this.ui.setHUD(false);document.getElementById('loading-screen').classList.add('hidden');document.getElementById('menu-screen').classList.remove('hidden');if(this.queryAutostart){document.getElementById('menu-screen').classList.add('hidden');this.startLevel(Number(new URLSearchParams(location.search).get('level')||0),true);}requestAnimationFrame(t=>this.loop(t));}
    startLevel(index,newRun=false){index=clamp(index,0,4);this.ui.setHUD(true);['menu-screen','level-screen','pause-screen','complete-screen','gameover-screen','victory-screen'].forEach(id=>document.getElementById(id).classList.add('hidden'));if(newRun||this.mode==='menu'){this.score=0;this.lives=3;}else this.lives=3;this.levelIndex=index;this.level=KG.Levels[index];this.world=new KG.World(this.level,this.audio,this.save);this.player=new KG.Player(this.level.spawn[0],this.level.spawn[1]);this.player.setCheckpoint(this.level.spawn[0],this.level.spawn[1]);this.missionTarget=this.level.ball?1:this.level.boss?5:this.level.mission.length;this.missionDoneCount=0;this.missionDone=false;this.cameraX=0;this.levelTime=0;this.finishLatch=false;this.mode='playing';this.ui.toast(this.level.objective,2200);this.ui.updateHUD(this);}
    goMenu(){this.mode='menu';this.ui.setHUD(false);document.getElementById('menu-screen').classList.remove('hidden');document.getElementById('boss-wrap').style.display='none';this.ui.refreshMenu();}
    togglePause(force){if(!this.world)return;const pause=force===undefined?this.mode==='playing':force;if(pause&&this.mode==='playing'){this.mode='paused';this.ui.showPause();}else if(!pause&&this.mode==='paused'){this.mode='playing';this.ui.hidePause();}}
    hurt(){if(this.player.invincible>0)return;this.lives--;this.player.invincible=1.4;this.audio.sfx('hurt');this.renderer.shake=13;this.renderer.flash=.6;this.ui.toast(this.lives>0?'Осторожно! Потеряна жизнь.':'Жизни закончились.');if(this.lives<=0){this.mode='gameover';this.ui.showGameOver();}else this.player.respawn();this.ui.updateHUD(this);}
    collect(it){if(it.type==='coin'){this.save.addCoins(1);this.score+=50;this.audio.sfx('coin');this.renderer.addParticles(it.x,it.y,'#ffd15b',8);}else{this.missionDoneCount++;this.score+=120;this.audio.sfx('collect');this.renderer.addParticles(it.x,it.y,'#ffb765',10);if(this.missionDoneCount>=this.missionTarget){this.missionDone=true;this.ui.toast('Задание выполнено! Ищи выход.',2100);}}this.ui.updateHUD(this);}
    complete(){if(this.finishLatch)return;this.finishLatch=true;this.mode='complete';this.audio.sfx('win');this.save.unlockLevel(this.levelIndex+1);this.save.setScore(this.score);let stars=1;if(this.levelTime<=this.level.par*1.15)stars=2;if(this.levelTime<=this.level.par&&this.lives===3)stars=3;this.save.setStars(this.levelIndex,stars);this.ui.showComplete(stars,this.levelTime);}
    showVictory(){this.mode='victory';this.audio.sfx('bossWin');this.save.setScore(this.score);this.ui.showVictory();}
    update(dt,time){if(this.input.consumePause())this.togglePause();if(this.mode!=='playing')return;this.levelTime+=dt;this.world.update(dt,time,this.player);this.player.update(dt,this.input,this.world,this.audio);if(this.player.y>1000)this.hurt();
      if(this.world.checkHazards(this.player))this.hurt();
      const ec=this.world.checkEnemyCollisions(this.player);if(ec){if(ec.type==='hurt')this.hurt();else{this.score+=180;this.audio.sfx('stomp');this.renderer.addParticles(ec.enemy.x,ec.enemy.y,'#b894ff',9);this.renderer.shake=5;}}
      const got=this.world.collect(this.player,time);got.forEach(it=>this.collect(it));
      if(this.world.checkpoint(this.player)){this.audio.sfx('checkpoint');this.ui.toast('Контрольная точка!');}
      if(this.world.ball&&this.world.basket&&this.missionDoneCount===0){const b=this.world.ball,bs=this.world.basket;if(b.x>bs.x+18&&b.x<bs.x+bs.w-18&&b.y>bs.y-70&&b.y<bs.y+bs.h){this.missionDoneCount=1;this.missionDone=true;this.score+=300;this.audio.sfx('win');this.ui.toast('Шар в корзине!');this.ui.updateHUD(this);setTimeout(()=>this.complete(),250);}}
      if(this.world.boss&&!this.world.boss.dead){const boss=this.world.boss;if(overlap(this.player.box(),boss.box())&&this.player.invincible<=0){if(boss.vulnerable&&this.player.vy>0&&this.player.y-this.player.h<boss.y-boss.h+38){boss.hp--;boss.flash=.3;this.player.vy=-620;this.score+=500;this.missionDoneCount=boss.maxHp-boss.hp;this.audio.sfx('boss');this.renderer.shake=10;this.renderer.addParticles(boss.x,boss.y-110,'#ff704f',16);this.ui.toast(`Попадание! Осталось ${boss.hp} HP`);this.ui.updateHUD(this);if(boss.hp<=0){boss.dead=true;this.missionDone=true;setTimeout(()=>this.complete(),600);}}else this.hurt();}}
      this.world._lastPlayerX=this.player.x;
      if((this.level.goalX&&this.missionDone&&this.player.x>this.level.goalX-65)||(this.level.house&&this.missionDone&&this.player.x>this.level.house[0]-80))this.complete();
      const target=clamp(this.player.x-this.renderer.w*.38,0,Math.max(0,this.level.width-this.renderer.w));this.cameraX+=(target-this.cameraX)*Math.min(1,dt*5.5);this.renderer.updateParticles(dt);this.audio.update(dt,this.mode);this.ui.updateHUD(this);
    }
    loop(now){const frame=Math.min((now-this.last)/1000,.05);this.last=now;this.acc+=frame;const time=now/1000;while(this.acc>=this.step){this.update(this.step,time);this.acc-=this.step;}if(this.world)this.renderer.render(this,time);requestAnimationFrame(t=>this.loop(t));}
  }
  KG.Game=Game;
})(window.KG = window.KG || {});
