(function(KG){
  'use strict';
  class Renderer {
    constructor(canvas,assets,save){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.assets=assets;this.save=save;this.w=innerWidth;this.h=innerHeight;this.dpr=1;this.shake=0;this.flash=0;this.particles=[];this.resize();addEventListener('resize',()=>this.resize());}
    resize(){this.w=innerWidth;this.h=innerHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.floor(this.w*this.dpr);this.canvas.height=Math.floor(this.h*this.dpr);this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.ctx.imageSmoothingEnabled=true;this.ctx.imageSmoothingQuality='high';}
    addParticles(x,y,color='#ffd35a',n=10){if(this.save.data.settings.reducedMotion)n=Math.max(2,Math.floor(n*.35));for(let i=0;i<n;i++)this.particles.push({x,y,vx:(Math.random()-.5)*220,vy:-80-Math.random()*220,life:.4+Math.random()*.45,r:3+Math.random()*5,color});}
    updateParticles(dt){for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=620*dt;}this.particles=this.particles.filter(p=>p.life>0);this.shake=Math.max(0,this.shake-dt*18);this.flash=Math.max(0,this.flash-dt*3);}
    roundRect(x,y,w,h,r){const c=this.ctx;c.beginPath();c.roundRect(x,y,w,h,r);}
    image(file,x,y,w,h,flip=false,alpha=1){const im=this.assets.get(file);if(!im)return;const c=this.ctx;c.save();c.globalAlpha=alpha;c.translate(x+w/2,y+h/2);if(flip)c.scale(-1,1);const s=Math.min(w/im.width,h/im.height);c.drawImage(im,-im.width*s/2,-im.height*s/2,im.width*s,im.height*s);c.restore();}
    background(level,cameraX){const c=this.ctx,im=this.assets.get(KG.Assets.backgrounds[level.background]);const g=c.createLinearGradient(0,0,0,this.h);const colors=[['#bfeaff','#7fcfff'],['#d7f4ff','#8ed9ff'],['#f9d8e5','#f6b8d6'],['#ffe0b3','#ffc29c'],['#6a5873','#30263b']][level.background];g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);c.fillStyle=g;c.fillRect(0,0,this.w,this.h);
      if(im){const scale=Math.max(this.w/im.width,this.h/im.height)*1.02,dw=im.width*scale,dh=im.height*scale,par=(cameraX*.08)%(Math.max(1,dw*.2));c.save();c.globalAlpha=.98;c.filter='saturate(1.07) contrast(1.02)';c.drawImage(im,-(dw-this.w)/2-par,0,dw,dh);c.restore();}
      c.save();const light=c.createRadialGradient(this.w*.58,this.h*.28,20,this.w*.58,this.h*.28,this.w*.65);light.addColorStop(0,'rgba(255,255,255,.18)');light.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=light;c.fillRect(0,0,this.w,this.h);c.restore();
      c.fillStyle='rgba(255,255,255,.52)';for(let i=0;i<6;i++){const x=(i*280-cameraX*.05+performance.now()*.01)%(this.w+350)-120,y=80+(i%3)*45;c.beginPath();c.arc(x,y,24,0,Math.PI*2);c.arc(x+28,y-12,22,0,Math.PI*2);c.arc(x+58,y,29,0,Math.PI*2);c.fill();}
    }
    platform(p,cameraX,moving=false){const c=this.ctx,x=p.x-cameraX,y=p.y;c.save();c.shadowColor='rgba(28,39,25,.28)';c.shadowBlur=18;c.shadowOffsetY=10;const g=c.createLinearGradient(x,y,x,y+p.h);g.addColorStop(0,moving?'#a7e18a':'#9bdd7c');g.addColorStop(.22,moving?'#86d36f':'#79c461');g.addColorStop(1,'#4e8b45');this.roundRect(x,y,p.w,p.h,18);c.fillStyle=g;c.fill();c.restore();c.fillStyle='rgba(255,255,255,.23)';this.roundRect(x+8,y+5,p.w-16,11,8);c.fill();
      c.fillStyle='rgba(85,57,35,.55)';for(let i=0;i<Math.min(7,Math.max(1,Math.floor(p.w/75)));i++){c.beginPath();c.ellipse(x+35+i*(p.w-70)/Math.max(1,Math.min(6,Math.floor(p.w/75)-1)),y+p.h-9,15,5,0,0,Math.PI*2);c.fill();}}
    spike(s,cameraX){const c=this.ctx,x=s.x-cameraX,n=Math.max(3,Math.floor(s.w/20));c.fillStyle='#d9d8de';c.strokeStyle='#5d5660';c.lineWidth=2;for(let i=0;i<n;i++){const q=x+i*s.w/n;c.beginPath();c.moveTo(q,s.y+s.h);c.lineTo(q+s.w/n/2,s.y-16);c.lineTo(q+s.w/n,s.y+s.h);c.closePath();c.fill();c.stroke();}}
    player(player,cameraX,time){const costume=KG.Assets.costumes[this.save.data.equippedCostume]||KG.Assets.costumes.default;let file=costume.image;if(costume.id==='default'){file=player.state==='jump'?KG.Assets.hero.jump:player.state==='fall'?KG.Assets.hero.fall:KG.Assets.hero.run;}const x=player.x-cameraX,y=player.y,flip=player.facing<0;const bob=player.state==='run'?Math.sin(time*11)*2:0,alpha=player.invincible>0&&Math.floor(player.invincible*14)%2===0?.35:1;const w=costume.id==='default'?112:104,h=costume.id==='default'?120:118;this.ctx.save();this.ctx.fillStyle='rgba(0,0,0,.18)';this.ctx.beginPath();this.ctx.ellipse(x,y+6,28,9,0,0,Math.PI*2);this.ctx.fill();this.ctx.restore();this.image(file,x-w/2,y-h+bob,w,h,flip,alpha);}
    item(it,cameraX,time){if(it.taken)return;const y=it.y+Math.sin(time*3+it.phase)*8,file=KG.Assets.items[it.type],size=it.type==='coin'?46:it.type==='butterfly'?55:52;this.ctx.save();this.ctx.shadowColor='rgba(255,224,106,.48)';this.ctx.shadowBlur=it.type==='coin'?18:10;this.image(file,it.x-cameraX-size/2,y-size/2,size,size);this.ctx.restore();}
    enemy(e,cameraX,time){if(e.dead)return;const file=KG.Assets.enemies[e.type],x=e.x-cameraX,y=e.y+Math.sin(time*5+e.phase)*2;this.ctx.save();this.ctx.fillStyle='rgba(0,0,0,.16)';this.ctx.beginPath();this.ctx.ellipse(x,y+3,24,7,0,0,Math.PI*2);this.ctx.fill();this.ctx.restore();this.image(file,x-36,y-70,72,72,e.vx<0);}
    ball(ball,cameraX){if(!ball)return;this.ctx.save();this.ctx.fillStyle='rgba(0,0,0,.16)';this.ctx.beginPath();this.ctx.ellipse(ball.x-cameraX,ball.y+ball.r+4,ball.r*.75,7,0,0,Math.PI*2);this.ctx.fill();this.ctx.restore();this.image(KG.Assets.items.ball,ball.x-cameraX-ball.r,ball.y-ball.r,ball.r*2,ball.r*2);}
    basket(b,cameraX){if(!b)return;const c=this.ctx,x=b.x-cameraX;c.save();c.shadowColor='rgba(0,0,0,.3)';c.shadowBlur=14;c.strokeStyle='#8f6039';c.lineWidth=10;c.strokeRect(x,b.y,b.w,b.h);c.strokeStyle='#e1c19a';c.lineWidth=2;for(let i=1;i<4;i++){c.beginPath();c.moveTo(x+i*b.w/4,b.y);c.lineTo(x+i*b.w/4,b.y+b.h);c.stroke();c.beginPath();c.moveTo(x,b.y+i*b.h/4);c.lineTo(x+b.w,b.y+i*b.h/4);c.stroke();}c.restore();}
    house(h,cameraX){if(!h)return;const c=this.ctx,x=h.x-cameraX;c.save();c.shadowColor='rgba(0,0,0,.3)';c.shadowBlur=18;c.fillStyle='#f0d7aa';this.roundRect(x-65,585,130,175,22);c.fill();c.fillStyle='#d96757';c.beginPath();c.moveTo(x-82,610);c.lineTo(x,510);c.lineTo(x+82,610);c.closePath();c.fill();c.fillStyle='#704a31';this.roundRect(x-20,680,40,80,10);c.fill();c.restore();}
    boss(b,cameraX,time){if(!b||b.dead)return;const x=b.x-cameraX,y=b.y,c=this.ctx;c.save();if(b.vulnerable){this.ctx.shadowColor='#ff6b3b';this.ctx.shadowBlur=34;}this.image(KG.Assets.boss,x-125,y-180,250,180,false);if(b.vulnerable){c.strokeStyle='rgba(255,236,132,.95)';c.lineWidth=6;c.beginPath();c.arc(x,y-78,80+Math.sin(time*9)*4,0,Math.PI*2);c.stroke();}c.restore();}
    orb(o,cameraX){const c=this.ctx;c.save();c.shadowColor='#ff512c';c.shadowBlur=18;const g=c.createRadialGradient(o.x-cameraX-4,o.y-4,2,o.x-cameraX,o.y,o.r);g.addColorStop(0,'#fff2a7');g.addColorStop(.45,'#ff9d38');g.addColorStop(1,'#dc3a1f');c.fillStyle=g;c.beginPath();c.arc(o.x-cameraX,o.y,o.r,0,Math.PI*2);c.fill();c.restore();}
    portal(level,cameraX,time,active){if(!level.goalX||!active)return;const c=this.ctx,x=level.goalX-cameraX,y=690;c.save();c.shadowColor='#c7b0ff';c.shadowBlur=28;c.strokeStyle='#a98cff';c.lineWidth=12;c.beginPath();c.arc(x,y,40+Math.sin(time*5)*3,0,Math.PI*2);c.stroke();c.restore();}
    checkpoint(cp,cameraX,active){if(!cp)return;const [x,y]=cp,c=this.ctx;c.save();c.translate(x-cameraX,y-55);c.fillStyle=active?'#ffd15b':'#b77a47';c.fillRect(-5,0,10,70);c.beginPath();c.moveTo(4,2);c.lineTo(46,17);c.lineTo(4,32);c.closePath();c.fill();c.restore();}
    drawParticles(cameraX){const c=this.ctx;for(const p of this.particles){c.globalAlpha=Math.max(0,p.life/.7);c.fillStyle=p.color;c.beginPath();c.arc(p.x-cameraX,p.y,p.r,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
    vignette(){const c=this.ctx,g=c.createRadialGradient(this.w/2,this.h/2,this.h*.18,this.w/2,this.h/2,Math.max(this.w,this.h)*.72);g.addColorStop(.65,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(6,12,18,.22)');c.fillStyle=g;c.fillRect(0,0,this.w,this.h);if(this.flash>0){c.fillStyle=`rgba(255,255,255,${Math.min(.35,this.flash*.25)})`;c.fillRect(0,0,this.w,this.h);}}
    render(game,time){const cam=game.cameraX+(this.shake?((Math.random()-.5)*this.shake):0),world=game.world;this.background(game.level,cam);world.platforms.forEach(p=>this.platform(p,cam,false));world.moving.forEach(p=>this.platform(p,cam,true));world.spikes.forEach(s=>this.spike(s,cam));this.house(world.house,cam);this.basket(world.basket,cam);this.checkpoint(game.level.checkpoint,cam,world.checkpointActivated);this.portal(game.level,cam,time,game.missionDone);world.items.forEach(it=>this.item(it,cam,time));world.enemies.forEach(e=>this.enemy(e,cam,time));this.ball(world.ball,cam);world.orbs.forEach(o=>this.orb(o,cam));this.boss(world.boss,cam,time);this.player(game.player,cam,time);this.drawParticles(cam);this.vignette();}
  }
  KG.Renderer=Renderer;
})(window.KG = window.KG || {});
