(function(KG){
  'use strict';
  class Renderer {
    constructor(canvas,assets,save){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.assets=assets;this.save=save;this.w=innerWidth;this.h=innerHeight;this.dpr=1;this.shake=0;this.flash=0;this.particles=[];this.resize();addEventListener('resize',()=>this.resize());}
    resize(){this.w=innerWidth;this.h=innerHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.floor(this.w*this.dpr);this.canvas.height=Math.floor(this.h*this.dpr);this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.ctx.imageSmoothingEnabled=true;this.ctx.imageSmoothingQuality='high';}
    addParticles(x,y,color='#ffd35a',n=10){if(this.save.data.settings.reducedMotion)n=Math.max(2,Math.floor(n*.35));for(let i=0;i<n;i++)this.particles.push({x,y,vx:(Math.random()-.5)*220,vy:-80-Math.random()*220,life:.4+Math.random()*.45,r:3+Math.random()*5,color});}
    addSplash(x,y){const n=this.save.data.settings.reducedMotion?6:18;for(let i=0;i<n;i++)this.particles.push({x:x+(Math.random()-.5)*28,y:y-4,vx:(Math.random()-.5)*260,vy:-150-Math.random()*260,life:.45+Math.random()*.4,r:2+Math.random()*5,color:i%3===0?'#ffffff':'#71d9ff'});}
    updateParticles(dt){for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=620*dt;}this.particles=this.particles.filter(p=>p.life>0);this.shake=Math.max(0,this.shake-dt*18);this.flash=Math.max(0,this.flash-dt*3);}
    roundRect(x,y,w,h,r){const c=this.ctx;c.beginPath();c.roundRect(x,y,w,h,r);}
    source(file){const ref=window.KG.AtlasSprites&&window.KG.AtlasSprites[file];if(ref){const im=this.assets.get(ref.atlas);return im?{im,sx:ref.x,sy:ref.y,sw:ref.w,sh:ref.h}:null;}const im=this.assets.get(file);return im?{im,sx:0,sy:0,sw:im.width,sh:im.height}:null;}
    image(file,x,y,w,h,flip=false,alpha=1,contain=true){const src=this.source(file);if(!src)return;const c=this.ctx;c.save();c.globalAlpha=alpha;c.translate(x+w/2,y+h/2);if(flip)c.scale(-1,1);if(contain){const scale=Math.min(w/src.sw,h/src.sh),dw=src.sw*scale,dh=src.sh*scale;c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,-dw/2,-dh/2,dw,dh);}else c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,-w/2,-h/2,w,h);c.restore();}
    spriteBaseline(file,x,feetY,drawH,flip=false,alpha=1,baseline=306,canvasH=320){const src=this.source(file);if(!src)return;const scale=drawH/canvasH,w=src.sw*scale,top=feetY-baseline*scale;const c=this.ctx;c.save();c.globalAlpha=alpha;c.translate(x,0);if(flip)c.scale(-1,1);c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,-w/2,top,w,src.sh*scale);c.restore();}
    frame(list,time,fps=8){if(!list||!list.length)return null;return list[Math.floor(time*fps)%list.length];}
    background(level,cameraX){const c=this.ctx,im=this.assets.get(KG.Assets.backgrounds[level.background]);const colors=[['#bfeaff','#7fcfff'],['#d7f4ff','#8ed9ff'],['#d7f1dc','#8fcfb0'],['#d9eeff','#9cc5ea'],['#7a5260','#261e2c']][level.background];const g=c.createLinearGradient(0,0,0,this.h);g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);c.fillStyle=g;c.fillRect(0,0,this.w,this.h);if(im){const scale=Math.max(this.w/im.width,this.h/im.height)*1.02,dw=im.width*scale,dh=im.height*scale,par=(cameraX*.035)%(Math.max(1,dw*.14));c.save();c.globalAlpha=.995;c.filter='saturate(1.05) contrast(1.025)';c.drawImage(im,-(dw-this.w)/2-par,-(dh-this.h)*.12,dw,dh);c.restore();}const light=c.createRadialGradient(this.w*.58,this.h*.24,20,this.w*.58,this.h*.24,this.w*.64);light.addColorStop(0,'rgba(255,255,255,.14)');light.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=light;c.fillRect(0,0,this.w,this.h);}
    drawWaterBand(level,cameraX,time){if(!level.fx?.water)return;const file=this.frame(KG.Assets.tiles.water,time,4),src=this.source(file);if(!src)return;const c=this.ctx,h=86,w=150,baseY=720;c.save();c.globalAlpha=level.background===3?.28:.38;c.globalCompositeOperation='screen';const start=Math.floor(cameraX/w)*w-w;for(let x=start;x<cameraX+this.w+w;x+=w)c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,x-cameraX,baseY,w,h);c.restore();}
    drawWaterfalls(level,cameraX,time){const arr=level.fx?.waterfalls||[];if(!arr.length)return;const file=this.frame(KG.Assets.tiles.waterfall,time,7);for(const [x,y,w,h] of arr){const c=this.ctx;c.save();c.globalAlpha=.72;c.globalCompositeOperation='screen';this.image(file,x-cameraX-w/2,y-h/2,w,h,false,.8,false);c.restore();}}
    drawTreeSway(level,cameraX,time){const arr=level.fx?.trees||[],file=KG.Assets.environment.treeValley,src=this.source(file);if(!src)return;for(let i=0;i<arr.length;i++){const [x,feetY,h]=arr[i],scale=h/src.sh,w=src.sw*scale,angle=Math.sin(time*1.4+i)*.018,c=this.ctx;c.save();c.translate(x-cameraX,feetY);c.rotate(angle);c.globalAlpha=.94;c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,-w/2,-h,w,h);c.restore();}}
    drawFlags(level,cameraX,time){const arr=level.fx?.flags||[];if(!arr.length)return;const file=this.frame(KG.Assets.tiles.flag,time,5);for(const [x,y,h] of arr)this.image(file,x-cameraX-h*.28,y-h,h*.6,h,false,.88);}
    drawFoliage(level,cameraX,time){const arr=level.fx?.foliage||[];if(!arr.length)return;const file=this.frame(KG.Assets.tiles.foliage,time,2);for(const [x,y] of arr)this.image(file,x-cameraX-42,y-78,84,78,false,.92);}
    drawWeather(level,time){const c=this.ctx;if(level.fx?.snow){c.save();c.fillStyle='rgba(255,255,255,.75)';for(let i=0;i<62;i++){const x=(i*127+time*(18+(i%5)*4))%(this.w+80)-40,y=(i*83+time*(38+(i%7)*5))%(this.h+90)-45,r=1+(i%3);c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}c.restore();}if(level.fx?.embers){c.save();for(let i=0;i<55;i++){const x=(i*139+time*(13+(i%5)*6))%(this.w+80)-40,y=this.h-((i*67+time*(45+(i%7)*9))%(this.h+100));c.fillStyle=i%2?'rgba(255,159,55,.72)':'rgba(255,80,35,.66)';c.beginPath();c.arc(x,y,1+(i%3),0,Math.PI*2);c.fill();}c.restore();}}
    environmentBack(level,cameraX,time){this.drawWaterBand(level,cameraX,time);this.drawWaterfalls(level,cameraX,time);this.drawTreeSway(level,cameraX,time);this.drawWeather(level,time);}environmentFront(level,cameraX,time){this.drawFlags(level,cameraX,time);this.drawFoliage(level,cameraX,time);}
    blockPlatform(p,cameraX,file){const src=this.source(file);if(!src)return;const c=this.ctx,x=p.x-cameraX;c.save();c.beginPath();c.rect(x,p.y,p.w,p.h+8);c.clip();const cell=108,ratio=src.sh/src.sw;for(let px=x-2;px<x+p.w+cell;px+=cell)c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,px,p.y-3,cell,cell*ratio);c.restore();}
    platform(p,cameraX,moving=false,level){const surface=level.surface;if(moving){const c=this.ctx,x=p.x-cameraX;c.save();c.shadowColor='rgba(0,0,0,.25)';c.shadowBlur=12;c.shadowOffsetY=7;const src=this.source(KG.Assets.tiles.wood);if(src)c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,x,p.y-7,p.w,42);else{c.fillStyle='#9a6339';this.roundRect(x,p.y,p.w,p.h,13);c.fill();}c.restore();return;}if((surface==='grass'||surface==='moss')&&p.h<60){const src=this.source(KG.Assets.tiles.grassPlatform);if(src){const x=p.x-cameraX,h=Math.max(82,p.w*.24);this.ctx.save();this.ctx.shadowColor='rgba(28,39,25,.24)';this.ctx.shadowBlur=15;this.ctx.shadowOffsetY=8;this.ctx.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,x,p.y-5,p.w,h);this.ctx.restore();return;}}const map={grass:KG.Assets.tiles.grass,moss:KG.Assets.tiles.moss,ice:KG.Assets.tiles.ice,lava:KG.Assets.tiles.lava};this.blockPlatform(p,cameraX,map[surface]||KG.Assets.tiles.grass);}
    spike(s,cameraX,level){const c=this.ctx,x=s.x-cameraX,n=Math.max(3,Math.floor(s.w/20));c.fillStyle=level.surface==='lava'?'#4c4245':'#d9d8de';c.strokeStyle=level.surface==='lava'?'#ff6b36':'#5d5660';c.lineWidth=2;for(let i=0;i<n;i++){const q=x+i*s.w/n;c.beginPath();c.moveTo(q,s.y+s.h);c.lineTo(q+s.w/n/2,s.y-16);c.lineTo(q+s.w/n,s.y+s.h);c.closePath();c.fill();c.stroke();}}
    player(player,cameraX,time){const costume=KG.Assets.costumes[this.save.data.equippedCostume]||KG.Assets.costumes.default,anims=costume.animations||KG.Assets.hero,state=player.state in anims?player.state:'idle',list=anims[state]||anims.idle,fps=state==='run'?10:state==='hurt'?7:5,file=this.frame(list,player.animTime,fps),x=player.x-cameraX,y=player.y,flip=player.facing<0,alpha=player.invincible>0&&Math.floor(player.invincible*14)%2===0?.38:1,drawH=costume.id==='default'?142:136,c=this.ctx;c.save();c.fillStyle='rgba(0,0,0,.20)';c.beginPath();c.ellipse(x,y+5,29,8,0,0,Math.PI*2);c.fill();c.restore();this.spriteBaseline(file,x,y,drawH,flip,alpha,306,320);}
    item(it,cameraX,time){if(it.taken)return;const y=it.y+Math.sin(time*3+it.phase)*8,file=KG.Assets.items[it.type],size=it.type==='coin'?48:it.type==='butterfly'?58:55,c=this.ctx;c.save();c.shadowColor=it.type==='coin'?'rgba(255,211,65,.65)':'rgba(255,255,255,.25)';c.shadowBlur=it.type==='coin'?18:9;this.image(file,it.x-cameraX-size/2,y-size/2,size,size);c.restore();}
    enemy(e,cameraX,time){if(e.dead)return;const frames=KG.Assets.enemies[e.type],file=this.frame(frames,e.anim+(e.phase*.1),e.type==='seagull'?10:7),x=e.x-cameraX,y=e.y,h=e.type==='seagull'?72:(e.type==='spikeball'||e.type==='rock'?68:76),w=h*1.2,c=this.ctx;c.save();c.fillStyle='rgba(0,0,0,.17)';c.beginPath();c.ellipse(x,y+4,24,7,0,0,Math.PI*2);c.fill();c.restore();if(e.type==='spikeball'||e.type==='rock'){const src=this.source(file);if(src){c.save();c.translate(x,y-h/2);c.rotate((e.anim*4.4)*(e.vx<0?-1:1));c.drawImage(src.im,src.sx,src.sy,src.sw,src.sh,-w/2,-h/2,w,h);c.restore();}}else this.image(file,x-w/2,y-h,w,h,e.vx<0);}
    ball(ball,cameraX){if(!ball)return;const c=this.ctx;c.save();c.fillStyle='rgba(0,0,0,.17)';c.beginPath();c.ellipse(ball.x-cameraX,ball.y+ball.r+4,ball.r*.78,7,0,0,Math.PI*2);c.fill();c.restore();this.image(KG.Assets.items.ball,ball.x-cameraX-ball.r,ball.y-ball.r,ball.r*2,ball.r*2);}
    basket(b,cameraX){if(!b)return;const c=this.ctx,x=b.x-cameraX;c.save();c.shadowColor='rgba(0,0,0,.3)';c.shadowBlur=14;c.strokeStyle='#8f6039';c.lineWidth=10;c.strokeRect(x,b.y,b.w,b.h);c.strokeStyle='#e1c19a';c.lineWidth=2;for(let i=1;i<4;i++){c.beginPath();c.moveTo(x+i*b.w/4,b.y);c.lineTo(x+i*b.w/4,b.y+b.h);c.stroke();c.beginPath();c.moveTo(x,b.y+i*b.h/4);c.lineTo(x+b.w,b.y+i*b.h/4);c.stroke();}c.restore();}
    house(h,cameraX){if(!h)return;const c=this.ctx,x=h.x-cameraX;c.save();c.shadowColor='rgba(0,0,0,.28)';c.shadowBlur=18;c.fillStyle='#f0d7aa';this.roundRect(x-65,585,130,175,22);c.fill();c.fillStyle='#d96757';c.beginPath();c.moveTo(x-82,610);c.lineTo(x,510);c.lineTo(x+82,610);c.closePath();c.fill();c.fillStyle='#704a31';this.roundRect(x-20,680,40,80,10);c.fill();c.restore();}
    boss(b,cameraX,time){if(!b)return;const x=b.x-cameraX,y=b.y,c=this.ctx;let file=KG.Assets.boss.idle;if(b.dead)file=KG.Assets.boss.defeated;else if(b.vulnerable)file=KG.Assets.boss.stunned;else if(b.state==='attackFire')file=KG.Assets.boss.attackFire;else if(b.state==='attackPunch')file=KG.Assets.boss.attackPunch;else if(b.state==='shield')file=KG.Assets.boss.shield;else if(b.state==='roar')file=KG.Assets.boss.roar;else if(b.state==='walk')file=KG.Assets.boss.walk;c.save();if(b.vulnerable){c.shadowColor='#ff6b3b';c.shadowBlur=36;}if(b.state==='attackPunch'&&!b.dead){c.strokeStyle='rgba(255,126,70,.5)';c.lineWidth=5;c.beginPath();c.arc(x,y-78,112+Math.sin(time*12)*8,0,Math.PI*2);c.stroke();}if(b.state==='shield'&&!b.dead){c.fillStyle='rgba(111,181,255,.12)';c.strokeStyle='rgba(145,211,255,.78)';c.lineWidth=5;c.beginPath();c.arc(x,y-88,104+Math.sin(time*5)*3,0,Math.PI*2);c.fill();c.stroke();}this.image(file,x-145,y-220,290,220,false,1);if(b.vulnerable&&!b.dead){c.strokeStyle='rgba(255,236,132,.92)';c.lineWidth=6;c.beginPath();c.arc(x,y-88,90+Math.sin(time*9)*4,0,Math.PI*2);c.stroke();}c.restore();}
    orb(o,cameraX){const c=this.ctx;c.save();c.shadowColor='#ff512c';c.shadowBlur=18;const g=c.createRadialGradient(o.x-cameraX-4,o.y-4,2,o.x-cameraX,o.y,o.r);g.addColorStop(0,'#fff2a7');g.addColorStop(.45,'#ff9d38');g.addColorStop(1,'#dc3a1f');c.fillStyle=g;c.beginPath();c.arc(o.x-cameraX,o.y,o.r,0,Math.PI*2);c.fill();c.restore();}
    portal(level,cameraX,time,active){if(!level.goalX||!active)return;const file=level.background===4?KG.Assets.items.portalGold:KG.Assets.items.portalBlue,x=level.goalX-cameraX,y=690;this.image(file,x-54,y-110,108,108,false,.96);}
    checkpoint(cp,cameraX,active,time){if(!cp)return;const [x,y]=cp,file=this.frame(KG.Assets.tiles.flag,time,5);this.image(file,x-cameraX-28,y-92,65,92,false,active?1:.65);}
    drawParticles(cameraX){const c=this.ctx;for(const p of this.particles){c.globalAlpha=Math.max(0,p.life/.7);c.fillStyle=p.color;c.beginPath();c.arc(p.x-cameraX,p.y,p.r,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
    speedLines(player){if(this.save.data.settings.reducedMotion||Math.abs(player.vx)<300||!player.onGround)return;const c=this.ctx,dir=Math.sign(player.vx);c.save();c.strokeStyle='rgba(255,255,255,.16)';c.lineWidth=2;for(let i=0;i<8;i++){const y=160+i*67+((player.animTime*120+i*19)%35),len=22+(i%4)*12,x=dir>0?25:this.w-25;c.beginPath();c.moveTo(x,y);c.lineTo(x-dir*len,y);c.stroke();}c.restore();}
    vignette(){const c=this.ctx,g=c.createRadialGradient(this.w/2,this.h/2,this.h*.18,this.w/2,this.h/2,Math.max(this.w,this.h)*.72);g.addColorStop(.68,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(6,12,18,.24)');c.fillStyle=g;c.fillRect(0,0,this.w,this.h);if(this.flash>0){c.fillStyle=`rgba(255,255,255,${Math.min(.35,this.flash*.25)})`;c.fillRect(0,0,this.w,this.h);}}
    render(game,time){const cam=game.cameraX+(this.shake?((Math.random()-.5)*this.shake):0),world=game.world;this.background(game.level,cam);this.environmentBack(game.level,cam,time);world.platforms.forEach(p=>this.platform(p,cam,false,game.level));world.moving.forEach(p=>this.platform(p,cam,true,game.level));world.spikes.forEach(s=>this.spike(s,cam,game.level));this.house(world.house,cam);this.basket(world.basket,cam);this.checkpoint(game.level.checkpoint,cam,world.checkpointActivated,time);this.portal(game.level,cam,time,game.missionDone);this.environmentFront(game.level,cam,time);world.items.forEach(it=>this.item(it,cam,time));world.enemies.forEach(e=>this.enemy(e,cam,time));this.ball(world.ball,cam);world.orbs.forEach(o=>this.orb(o,cam));this.boss(world.boss,cam,time);this.player(game.player,cam,time);this.speedLines(game.player);this.drawParticles(cam);this.vignette();}
  }
  KG.Renderer=Renderer;
})(window.KG = window.KG || {});
