(function(KG){
  'use strict';
  class UI {
    constructor(game,save){this.game=game;this.save=save;this.toastTimer=0;this.returnMode='menu';this.bind();}
    el(id){return document.getElementById(id);}
    bind(){this.el('btn-new').onclick=()=>this.game.startLevel(0,true);this.el('btn-continue').onclick=()=>this.showLevelSelect();this.el('btn-levels').onclick=()=>this.showLevelSelect();this.el('btn-shop-main').onclick=()=>this.openShop();this.el('btn-shop-hud').onclick=()=>this.openShop();this.el('btn-settings').onclick=()=>this.openSettings();this.el('btn-pause').onclick=()=>this.game.togglePause(true);this.el('btn-resume').onclick=()=>this.game.togglePause(false);this.el('btn-restart').onclick=()=>{this.hide('pause-screen');this.game.startLevel(this.game.levelIndex,false);};this.el('btn-menu').onclick=()=>{this.hide('pause-screen');this.game.goMenu();};this.el('btn-next').onclick=()=>{this.hide('complete-screen');if(this.game.levelIndex<4)this.game.startLevel(this.game.levelIndex+1,false);else this.game.showVictory();};this.el('btn-complete-shop').onclick=()=>this.openShop('complete-screen');this.el('btn-shop-close').onclick=()=>this.closeShop();this.el('btn-settings-close').onclick=()=>this.closeSettings();this.el('btn-over-retry').onclick=()=>{this.hide('gameover-screen');this.game.startLevel(this.game.levelIndex,false);};this.el('btn-over-menu').onclick=()=>{this.hide('gameover-screen');this.game.goMenu();};this.el('btn-win-again').onclick=()=>{this.hide('victory-screen');this.game.startLevel(0,true);};this.el('btn-win-shop').onclick=()=>this.openShop('victory-screen');this.el('btn-level-close').onclick=()=>this.hide('level-screen');this.el('setting-music').onchange=e=>{this.save.data.settings.music=e.target.checked;this.save.commit();};this.el('setting-sfx').onchange=e=>{this.save.data.settings.sfx=e.target.checked;this.save.commit();};this.el('setting-volume').oninput=e=>{this.save.data.settings.volume=Number(e.target.value);this.save.commit();};this.el('setting-motion').onchange=e=>{this.save.data.settings.reducedMotion=e.target.checked;this.save.commit();};this.el('btn-reset-save').onclick=()=>{if(confirm('Сбросить прогресс, монеты и костюмы?')){this.save.resetProgress();this.refreshMenu();this.renderShop();this.renderLevels();this.toast('Прогресс сброшен.');}};}
    show(id){this.el(id).classList.remove('hidden');}hide(id){this.el(id).classList.add('hidden');}
    drawSpriteCanvas(file,canvas,maxH=150){if(!canvas)return;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);const ref=window.KG.AtlasSprites&&window.KG.AtlasSprites[file];let im,sx=0,sy=0,sw,sh;if(ref){im=this.game.assets.get(ref.atlas);if(!im)return;sx=ref.x;sy=ref.y;sw=ref.w;sh=ref.h;}else{im=this.game.assets.get(file);if(!im)return;sw=im.width;sh=im.height;}const scale=Math.min((canvas.width-12)/sw,maxH/sh),dw=sw*scale,dh=sh*scale;c.drawImage(im,sx,sy,sw,sh,(canvas.width-dw)/2,(canvas.height-dh)/2,dw,dh);}
    setHUD(visible){this.el('hud').style.display=visible?'flex':'none';this.el('combo-wrap').style.display='none';if(!visible)this.el('boss-wrap').style.display='none';}
    updateCombo(game){const el=this.el('combo-wrap');if(!el)return;if(game.combo>=2&&game.mode==='playing'){el.style.display='block';this.el('combo-text').textContent=`COMBO x${game.combo}`;}else el.style.display='none';}
    toast(text,ms=1900){clearTimeout(this.toastTimer);const t=this.el('toast');t.textContent=text;t.classList.add('show');this.toastTimer=setTimeout(()=>t.classList.remove('show'),ms);}
    refreshMenu(){this.el('menu-coins').textContent=this.save.data.coins;this.el('menu-best').textContent=this.save.data.bestScore;this.el('btn-continue').disabled=false;this.el('btn-continue').textContent=this.save.data.highestLevel>0?'Продолжить':'Выбор уровня';const costume=KG.Assets.costumes[this.save.data.equippedCostume]||KG.Assets.costumes.default;this.drawSpriteCanvas(costume.preview,this.el('menu-hero'),220);}
    updateHUD(game){this.el('hud-level').textContent=`${game.levelIndex+1}. ${game.level.name}`;this.el('hud-task').textContent=game.level.objective;this.el('hud-progress').textContent=game.world.boss?`Босс: ${game.world.boss.hp} HP`:`${game.missionDoneCount} / ${game.missionTarget}`;this.el('hud-coins').textContent=this.save.data.coins;this.el('hud-score').textContent=game.score;this.el('hud-lives').textContent='❤️'.repeat(game.lives)+'🤍'.repeat(Math.max(0,3-game.lives));if(game.world.boss){const b=game.world.boss;this.el('boss-wrap').style.display='block';this.el('boss-fill').style.width=(b.hp/b.maxHp*100)+'%';const label=this.el('boss-phase');if(label)label.textContent=b.vulnerable?'УЯЗВИМ!':b.state==='attackFire'?'Огненные шары':b.state==='attackPunch'?'Рывок':b.state==='shield'?'Щит':'Глиняный Хаос';}else this.el('boss-wrap').style.display='none';this.updateCombo(game);}
    showLevelSelect(){this.renderLevels();this.show('level-screen');}
    renderLevels(){const host=this.el('level-grid');host.innerHTML='';KG.Levels.forEach((L,i)=>{const locked=i>this.save.data.highestLevel,card=document.createElement('button');card.className='level-card'+(locked?' locked':'');card.disabled=locked;card.innerHTML=`<span class="level-number">${i+1}</span><strong>${L.name}</strong><small>${L.subtitle}</small><span class="stars">${'★'.repeat(this.save.data.stars[i]||0)}${'☆'.repeat(3-(this.save.data.stars[i]||0))}</span>${locked?'<span class="lock">🔒</span>':''}`;card.onclick=()=>{this.hide('level-screen');this.game.startLevel(i,false);};host.appendChild(card);});}
    openShop(returnScreen=null){this.returnMode=this.game.mode;if(returnScreen)this.hide(returnScreen);if(this.game.mode==='playing')this.game.mode='shop';this.renderShop();this.show('shop-screen');this._returnScreen=returnScreen;}
    closeShop(){this.hide('shop-screen');if(this._returnScreen)this.show(this._returnScreen);else if(this.returnMode==='playing'||this.returnMode==='paused')this.game.mode=this.returnMode;this._returnScreen=null;}
    renderShop(){this.el('shop-coins').textContent=this.save.data.coins;const host=this.el('shop-grid');host.innerHTML='';Object.values(KG.Assets.costumes).forEach(c=>{const own=this.save.ownsCostume(c.id),active=this.save.data.equippedCostume===c.id,card=document.createElement('div');card.className='shop-card'+(active?' active':'');card.innerHTML=`<canvas width="260" height="160" aria-label="${c.name}"></canvas><div><strong>${c.name}</strong><small>${c.description}</small></div><button>${active?'Надето':own?'Надеть':`Купить · 🪙 ${c.price}`}</button>`;this.drawSpriteCanvas(c.preview,card.querySelector('canvas'),145);card.querySelector('button').onclick=()=>{if(active)return;if(own){this.save.equipCostume(c.id);this.toast(`${c.name} надет.`);}else if(this.save.buyCostume(c.id,c.price)){this.game.audio.sfx('coin');this.toast(`${c.name} куплен.`);}else{this.toast('Не хватает монет.');return;}this.renderShop();this.refreshMenu();this.updateHUD(this.game);};host.appendChild(card);});}
    openSettings(){const s=this.save.data.settings;this.el('setting-music').checked=s.music;this.el('setting-sfx').checked=s.sfx;this.el('setting-volume').value=s.volume;this.el('setting-motion').checked=s.reducedMotion;this.show('settings-screen');}closeSettings(){this.hide('settings-screen');}showPause(){this.show('pause-screen');}hidePause(){this.hide('pause-screen');}
    showComplete(stars,time){this.el('complete-title').textContent=`Уровень ${this.game.levelIndex+1} пройден!`;this.el('complete-stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);this.el('complete-stats').textContent=`Время: ${time.toFixed(1)} сек · Очки: ${this.game.score} · Монеты: ${this.save.data.coins}`;this.el('btn-next').textContent=this.game.levelIndex===4?'Финал':'Следующий уровень';this.show('complete-screen');}
    showGameOver(){this.show('gameover-screen');}showVictory(){this.el('victory-score').textContent=`Итоговый счёт: ${this.game.score} · Монеты: ${this.save.data.coins}`;this.show('victory-screen');this.confetti();}
    confetti(){const canvas=this.el('victory-fx'),c=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;let pieces=Array.from({length:130},()=>({x:Math.random()*canvas.width,y:-Math.random()*canvas.height,vx:(Math.random()-.5)*2.2,vy:2+Math.random()*4.2,r:3+Math.random()*6,a:Math.random()*6.3,h:Math.random()*360}));const tick=()=>{if(this.el('victory-screen').classList.contains('hidden'))return;c.clearRect(0,0,canvas.width,canvas.height);for(const p of pieces){p.x+=p.vx;p.y+=p.vy;p.a+=.05;if(p.y>canvas.height+20){p.y=-20;p.x=Math.random()*canvas.width;}c.save();c.translate(p.x,p.y);c.rotate(p.a);c.fillStyle=`hsl(${p.h} 85% 60%)`;c.fillRect(-p.r,-p.r/2,p.r*2,p.r);c.restore();}requestAnimationFrame(tick);};tick();}
  }
  KG.UI=UI;
})(window.KG = window.KG || {});
